### ISSUE TITLE
How do I install it?

### ISSUE THREAD

**Issue by robdmoore** [mbinic/vscode-tgit#1]
If I use the extension search inside of VS Code I can't seem to find this extension. Do I need to manually build it and install it or am I just searching for the wrong thing?

I tried searching for:

* tgit
* tortoise
* vscode-tgit

Thanks

**Comment by mbinic** [comment]
Hello,

Nope, you're searching for the right thing, it's just not there yet :) It'll be in the extension gallery within a couple of hours. I'll post here once it's up.

**Comment by mbinic** [comment]
Aaaand, it's live [on the marketplace](https://marketplace.visualstudio.com/items?itemName=mbinic.tgit-cmds). Looking forward to feedback.
Cheers,
