### ISSUE TITLE
No working directory found

### ISSUE THREAD

**Issue by jmartensson** [mbinic/vscode-tgit#2]
Visual Studio Code: 1.9.1
TortoiseGIT: 2.5.0
Windows: 7 Enterprise

I get this error when trying to commit

![image](https://user-images.githubusercontent.com/9382342/35083708-b23e17b0-fc20-11e7-81f6-d15d5ba52760.png)

**Comment by jOOc** [comment]
The issue was that my GIT repository was on a network drive.
Its working if the repo is on a local drive

**Comment by mbinic** [comment]
I'll give it a try and see what I can do to fix it.
Just to make sure TortoiseGIT supports it: Do you get the same error if you right click on the repo folder and choose Commit in Windows Explorer?

**Comment by jOOc** [comment]
Hi, no it works in windows explorer

**Comment by hahoyer** [comment]
Have this issue too. Is there any solution?

**Comment by mbinic** [comment]
Version 1.4.0 released, this should now be fixed.
@jmartensson , @hahoyer, please let me know if everything's ok at your end and I can close this issue.

**Comment by hahoyer** [comment]
Still getting above error message. (Windows 10)

**Comment by mbinic** [comment]
Hmm, that's strange. I did check everything in before publishing 1.4.0.
I tested it on another machine just now, and everything worked fine. And that's despite me accessing a network share through VPN so slow that it took Windows Explorer 2mins to event load the contents of the folder.

@hahoyer , you replied very quickly after I published the new version (and I'm thankful :) ). Can you please verify that you have 1.4.0 and that you've reloaded VS Code?

The only things that come to mind atm is that:
1. the folder you're opening in VS Code is not a git repo or inside a git repo, i.e. there's no `.git` folder in it nor its parent folders
2. Node's `child_process.exec` is choking on a special character in your network path

In case that checks out, maybe you can help me debug the issue?

**Comment by hahoyer** [comment]
In my use of tgit, all variants actually occur: a) vs-code was opened on a directory where some subdirectories are git-repos. b) vs-code was opened on a directory that is part of a git-repo.

Please try to allow these scenarios! I am totally annoyed by these poor built-in git bindings.

**Comment by hahoyer** [comment]
Ah, just tested the case b) That works!

**Comment by mbinic** [comment]
Ah, got it, thanks for that. It's not the scenario I had in mind, but sure - if a file is open, it can look at that file's parent folders too. I'll post back here once it's ready.

**Comment by mbinic** [comment]
@hahoyer , 1.4.1 just published. Now you should be able to run commands when your workspace is not a git repo, but the opened file is part of one.
Please try it out and let me know if it works at your end.

**Comment by hahoyer** [comment]
It works now.
Scenario: VS-Code has been opened on a directory with multiple subdirectories. Some of them containing a .git-directory some of them not.
Tried commit-command while in different files. If inside of a git-controlled directory the commit for that repo is presented.
When in a file that is not under git-control it presents the commit for the last repo - there is no last repo the error message "The 'commit' command requires an existing file or folder to be open." is presented.
So for me the is ok. 
Thank you.
